### ISSUE TITLE
When the Github API goes down, The Contributor Worker Can't hear you scream

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#1005]
Looks like the Github API went down for a spell last night, and killed a contributor worker. Just one. So perhaps they are dividing or load balancing in a way that affected one instance and not others. OR, we did well at the bad timing awards. Here's the error: (deidentified the user, will post that in slack)

```
[85425] workers.contributor_worker.52900 [INFO] Search query did not return any results, moving on...

[85425] workers.contributor_worker.52900 [INFO] Updated cntrb_created_at and cntrb_last_used columns for existing tuple in the contributors table with email: xxx.lagxxxat.k@gmail.com

[85425] workers.contributor_worker.52900 [INFO] Hitting endpoint: https://api.github.com/search/users?q=abrxxxaham.xxx.k@gmail.com+in:email+fullname:Abrahxxxam+K. ...

[85425] workers.contributor_worker.52900 [ERROR] Worker ran into an error for task: {'job_type': 'MAINTAIN', 'models': ['contributors'], 'display_name': 'contributors model for url: https://github.com/scikit-learn/scikit-learn', 'given': {'git_url': 'https://github.com/scikit-learn/scikit-learn'}}

[85425] workers.contributor_worker.52900 [ERROR] Printing traceback...

[85425] workers.contributor_worker.52900 [ERROR] Traceback (most recent call last):
  File "/Users/gogginsS/github/virtualenvs/augur-czi/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/Users/gogginsS/github/virtualenvs/augur-czi/lib/python3.8/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gogginsS/github/virtualenvs/augur-czi/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/Users/gogginsS/github/virtualenvs/augur-czi/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/Users/gogginsS/github/virtualenvs/augur-czi/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/Users/gogginsS/github/virtualenvs/augur-czi/lib/python3.8/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/Users/gogginsS/github/virtualenvs/augur-czi/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x145e252e0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gogginsS/github/virtualenvs/augur-czi/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/gogginsS/github/virtualenvs/augur-czi/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/Users/gogginsS/github/virtualenvs/augur-czi/lib/python3.8/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /search/users?q=abraham.lagat.k@gmail.com+in:email+fullname:Abraham+K. (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x145e252e0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gogginsS/github/chaoss/augur-czi3/workers/worker_base.py", line 330, in collect
    model_method(message, repo_id)
  File "/Users/gogginsS/github/chaoss/augur-czi3/workers/contributor_worker/contributor_worker.py", line 213, in contributors_model
    r = requests.get(url=url, headers=self.headers)
  File "/Users/gogginsS/github/virtualenvs/augur-czi/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/gogginsS/github/virtualenvs/augur-czi/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/gogginsS/github/virtualenvs/augur-czi/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/gogginsS/github/virtualenvs/augur-czi/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/Users/gogginsS/github/virtualenvs/augur-czi/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /search/users?q=abraham.lagat.k@gmail.com+in:email+fullname:Abraham+K. (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x145e252e0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

[85425] workers.contributor_worker.52900 [INFO] This task inserted 347 tuples before failure.

[85425] workers.contributor_worker.52900 [INFO] Notifying broker and logging task failure in database...

[1253] workers.contributor_worker.52900 [INFO] Sending to work on task: {'job_type': 'MAINTAIN', 'models': ['contributors'], 'display_name': 'contributors model for url: https://github.com/samtools/htsjdk', 'given': {'git_url': 'https://github.com/samtools/htsjdk'}}
[85425] workers.contributor_worker.52900 [ERROR] Recorded job error in the history table for: {'job_type': 'MAINTAIN', 'models': ['contributors'], 'display_name': 'contributors model for url: https://github.com/scikit-learn/scikit-learn', 'given': {'git_url': 'https://github.com/scikit-learn/scikit-learn'}, 'worker_id': 'workers.contributor_worker.52900'}

[85425] workers.contributor_worker.52900 [INFO] Updated job process for model: contributors

[85425] workers.contributor_worker.52900 [DEBUG] Closing database connections

[85425] workers.contributor_worker.52900 [INFO] Collection process finished
[7495] workers.contributor_worker.52900 [INFO] Starting data collection process

[7495] workers.contributor_worker.52900 [INFO] Making database connections
[7495] workers.contributor_worker.52900 [INFO] ['worker_history', 'worker_job']
[7495] workers.contributor_worker.52900 [INFO] Found max id for history_id column in the worker_history table: 159444

[7495] workers.contributor_worker.52900 [INFO] Initializing API key.
[7495] workers.contributor_worker.52900 [INFO] Trying initialization.
[7495] workers.contributor_worker.52900 [INFO] Getting rate limit info for oauth: {'oauth_id': 0, 'access_token': xxx
```

**Comment by sgoggins** [comment]
The fix is probably to recognize the error and move on to the next user, @ABrain7710 ... @gabe-heim can probably give you a five minute pointer.

**Comment by sgoggins** [comment]
This appears to be an *extremely* anomalous phenomena, and I have been unable to replicate it, so I am closing the issue.
