### ISSUE TITLE
GitLab Merge Request Worker: Rate Limit Management Timeout and Other errors

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#1072]
Please help us help you by filling out the following sections as thoroughly as you can.

**Description:**
When I start the merge request worker on the `gitlab-issues+releases-patch` branch, I get one Merge request record partially inserted, these errors: 

```
(augur-gitlab) ➜  gitlab_merge_request_worker git:(gitlab-issues+releases-patch) ✗ cat gitlab_merge_request_worker_51200_collection.err 
2020-12-28 16:41:48,852 [PID: 2237] workers.gitlab_merge_request_worker.51200 [register_task_failure() in worker_base.py:L1154] [ERROR]: Worker ran into an error for task: {'job_type': 'MAINTAIN', 'models': ['merge_requests'], 'display_name': 'merge_requests model for url: https://gitlab.com/gitlab-org/gitlab-foss', 'given': {'git_url': 'https://gitlab.com/gitlab-org/gitlab-foss'}, 'focused_task': 1}

2020-12-28 16:41:48,852 [PID: 2237] workers.gitlab_merge_request_worker.51200 [register_task_failure() in worker_base.py:L1155] [ERROR]: Printing traceback...

2020-12-28 16:41:48,853 [PID: 2237] workers.gitlab_merge_request_worker.51200 [register_task_failure() in worker_base.py:L1157] [ERROR]: Traceback (most recent call last):
  File "/Users/sgoggins/github/CHAOSS/augur-gitlab/workers/worker_base.py", line 330, in collect
    model_method(message, repo_id)
  File "/Users/sgoggins/github/CHAOSS/augur-gitlab/workers/gitlab_merge_request_worker/gitlab_merge_request_worker.py", line 147, in merge_requests_model
    self.query_mr_meta(self.pr_id_inc, pr_dict['iid'], url_encoded_format_project_address)
  File "/Users/sgoggins/github/CHAOSS/augur-gitlab/workers/gitlab_merge_request_worker/gitlab_merge_request_worker.py", line 171, in query_mr_meta
    head = {'sha': mr_dict['diff_refs']['head_sha'],
TypeError: 'NoneType' object is not subscriptable

2020-12-28 16:41:48,890 [PID: 2237] workers.gitlab_merge_request_worker.51200 [register_task_failure() in worker_base.py:L1194] [ERROR]: Recorded job error in the history table for: {'job_type': 'MAINTAIN', 'models': ['merge_requests'], 'display_name': 'merge_requests model for url: https://gitlab.com/gitlab-org/gitlab-foss', 'given': {'git_url': 'https://gitlab.com/gitlab-org/gitlab-foss'}, 'focused_task': 1, 'worker_id': 'workers.gitlab_merge_request_worker.51200'}

2020-12-28 16:45:31,047 [PID: 4703] workers.gitlab_merge_request_worker.51200 [update_gh_rate_limit() in worker_base.py:L1314] [ERROR]: Could not get reset time from headers because of error: 'x-ratelimit-reset'
2020-12-28 16:46:30,506 [PID: 4703] workers.gitlab_merge_request_worker.51200 [update_gh_rate_limit() in worker_base.py:L1314] [ERROR]: Could not get reset time from headers because of error: 'x-ratelimit-reset'
2020-12-28 16:47:29,946 [PID: 4703] workers.gitlab_merge_request_worker.51200 [update_gh_rate_limit() in worker_base.py:L1314] [ERROR]: Could not get reset time from headers because of error: 'x-ratelimit-reset'
2020-12-28 16:48:29,426 [PID: 4703] workers.gitlab_merge_request_worker.51200 [update_gh_rate_limit() in worker_base.py:L1314] [ERROR]: Could not get reset time from headers because of error: 'x-ratelimit-reset'
2020-12-28 16:49:28,861 [PID: 4703] workers.gitlab_merge_request_worker.51200 [update_gh_rate_limit() in worker_base.py:L1314] [ERROR]: Could not get reset time from headers because of error: 'x-ratelimit-reset'
2020-12-28 16:50:28,440 [PID: 4703] workers.gitlab_merge_request_worker.51200 [update_gh_rate_limit() in worker_base.py:L1314] [ERROR]: Could not get reset time from headers because of error: 'x-ratelimit-reset'
2020-12-28 16:51:27,816 [PID: 4703] workers.gitlab_merge_request_worker.51200 [update_gh_rate_limit() in worker_base.py:L1314] [ERROR]: Could not get reset time from headers because of error: 'x-ratelimit-reset'
2020-12-28 16:52:27,219 [PID: 4703] workers.gitlab_merge_request_worker.51200 [update_gh_rate_limit() in worker_base.py:L1314] [ERROR]: Could not get reset time from headers because of error: 'x-ratelimit-reset'
2020-12-28 16:53:26,615 [PID: 4703] workers.gitlab_merge_request_worker.51200 [update_gh_rate_limit() in worker_base.py:L1314] [ERROR]: Could not get reset time from headers because of error: 'x-ratelimit-reset'
2020-12-28 16:54:26,060 [PID: 4703] workers.gitlab_merge_request_worker.51200 [update_gh_rate_limit() in worker_base.py:L1314] [ERROR]: Could not get reset time from headers because of error: 'x-ratelimit-reset'
```

**How to reproduce:**
1. Do  a regular clone of augur.
2. Use database credentials from slack, or comment here to request them
3. set the `switch` parameter to 1, as below: 
```
        "gitlab_merge_request_worker": {
            "port": 51200,
            "switch": 1,
            "workers": 1
        },
```
4. Start Augur using `nohup augur backend start >logs/test.log 2>logs/test.err &
5. Wait 30-60 seconds, then switch from the root directory of Augur to `logs/workers/gitlab_merge_request_worker` directory and you will see three files. The `.err`  file is the first to look at: 
```
-rw-r--r--  1 sgoggins  staff    197952 Dec 29 09:49 gitlab_merge_request_worker_51200_collection.err
-rw-r--r--  1 sgoggins  staff  65431183 Dec 29 09:49 gitlab_merge_request_worker_51200_collection.log
-rw-r--r--  1 sgoggins  staff      5686 Dec 29 09:58 gitlab_merge_request_worker_51200_server.log
```

**Expected behavior:**
Regular data collection

**Log files**
Above 

**Software versions:**
 - Augur: `gitlab-issues+releases-patch` branch
 - OS: (I'm testing on Mac OSX Catalina)
 - **PYTHON** : Not all libraries are on pip for `python 3.9`, so you much build your virtual environment using `python 3.8.x` at this time.  This is usually resolved in a month or two following a major release.

**Comment by sgoggins** [comment]
@mrsaicharan1 : It may be that you and @abhinavbajpai2012 can discuss solutions. @gabe-heim and I are also happy to zoom if there are some new complexities.

**Comment by abhinavbajpai2012** [comment]
@sgoggins the first bug is just key not found in dictionary. I will fix it this week. The second one is a bit serious because the data is normalized in the gitlab DB (API) while our's isn't, due to which multiple API calls are to be made.

**Comment by sgoggins** [comment]
@abhinavbajpai2012 : How are we doing on closing this one out?

**Comment by sgoggins** [comment]
@abhinavbajpai2012 : Did we get this one?

**Comment by Kashyap03-K** [comment]
Hello i am a beginner and as this is a good first issue can i work on this one ?
