### ISSUE TITLE
I am facing a issue in installing augur to my local machine, can you please help

### ISSUE THREAD

**Issue by Dhruv-Sachdev1313** [chaoss/augur#1134]
**I did make a database as given in the documentation and ran make install and followed the procedure, but it failed 
So I tried several times with different approach 
1-after running make install when it asks for database and gives 3 options, I chose- 1) initialize a new database AND install the schema? 
then I followed the procedure and  it creates the database but fails to connect it, it shows**

Background on this error at: http://sqlalche.me/e/13/e3q8)

**********************************
Schema created.
**********************************

DB created.
Would you like to install Augur's frontend dependencies? [Y/n] n
Skipping frontend dependencies...
[10302] augur.application [ERROR] Unable to connect to the database. Terminating...
Traceback (most recent call last):
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 304, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 241, in _do_get
    return self._create_connection()
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 508, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  database "augur" does not exist

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/bin/augur", line 11, in <module>
    load_entry_point('augur==0.14.0', 'console_scripts', 'augur')()
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/augur/cli/__init__.py", line 12, in new_func
    ctx.obj = Application()
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/augur/application.py", line 62, in __init__
    self.database, self.operations_database, self.spdx_database = self._connect_to_database()
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/augur/application.py", line 96, in _connect_to_database
    raise(e)
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/augur/application.py", line 89, in _connect_to_database
    engine.connect().close()
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2263, in connect
    return self._connection_cls(self, **kwargs)
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 104, in __init__
    else engine.raw_connection()
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2369, in raw_connection
    return self._wrap_pool_connect(
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2339, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1583, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 304, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 241, in _do_get
    return self._create_connection()
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 508, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  database "augur" does not exist

(Background on this error at: http://sqlalche.me/e/13/e3q8)
make: *** [install] Error 1

**Now I ran make clean and made a database beforehand manually as it was directed in documentation
now I guess it connected to database but gave me an error, which I couldn't figure out , can you please help - it showed -**

**********************************
Generating configuration file...
**********************************

CLI: [config.init] [INFO] Config written to /Users/dhruvsachdev/.augur/augur.config.json
CLI: [config.init_frontend] [ERROR] Error writing frontend.config.json [Errno 2] No such file or directory: '/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/frontend/frontend.config.json'
CLI: [db.check_pgpass_credentials] [INFO] Credentials found in $HOME/.pgpass
CLI: [db.check_pgpass_credentials] [INFO] Credentials found in $HOME/.pgpass
Traceback (most recent call last):
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/bin/augur", line 11, in <module>
    load_entry_point('augur==0.14.0', 'console_scripts', 'augur')()
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/augur/cli/__init__.py", line 13, in new_func
    return ctx.invoke(f, ctx.obj, *args, **kwargs)
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/augur/cli/db.py", line 214, in create_schema
    run_psql_command_in_database(augur_app, '-f', 'schema/create_schema.sql')
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/augur/cli/db.py", line 296, in run_psql_command_in_database
    call(['psql', '-h', augur_app.config.get_value('Database', 'host'),\
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'psql'

**********************************
Schema created.
**********************************

Would you like to install Augur's frontend dependencies? [Y/n] n
Skipping frontend dependencies...
Traceback (most recent call last):
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "augur_operations.augur_settings" does not exist
LINE 2:         SELECT value FROM augur_operations.augur_settings WH...
                                  ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/bin/augur", line 11, in <module>
    load_entry_point('augur==0.14.0', 'console_scripts', 'augur')()
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/augur/cli/__init__.py", line 13, in new_func
    return ctx.invoke(f, ctx.obj, *args, **kwargs)
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/augur/cli/db.py", line 251, in get_api_key
    print(augur_app.database.execute(get_api_key_sql).fetchone()[0])
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2235, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/Users/dhruvsachdev/.virtualenvs/augur_env/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "augur_operations.augur_settings" does not exist
LINE 2:         SELECT value FROM augur_operations.augur_settings WH...
                                  ^

[SQL: 
        SELECT value FROM augur_operations.augur_settings WHERE setting='augur_api_key';
    ]
(Background on this error at: http://sqlalche.me/e/13/f405)
make: *** [install] Error 1

**Comment by Nebrethar** [comment]
@sgoggins do we have a database we could provide for @Dhruv-Sachdev1313 for testing purposes?

**Comment by sgoggins** [comment]
There are 3 main issues developers encounter when first installing Augur: 
1. The absence of a `gcc` or `fortran` copiler, required by numpy and nltk python libraries. 
2. Conflicting versions of Python: The fix is platform specific. On Max OSX, more often than not multiple versions of python have been installed by the OS, brew, Anaconda, or a combination of both. The result is some python commands are drawn from different paths because of how they are linked in `/usr/local/bin`
3. Multiple, or conflicting versions of postgresql. Sometimes, the absence of a functional `psql` function at the command line results.

**Comment by sgoggins** [comment]
We have time setup this evening, US time, to resolve your specific configuration! 👍

**Comment by czyke** [comment]
@sgoggins Hi, Sean, same problem I encounted in installation phase, could you pls show us the processes of how to solve it. Thanks.
