### ISSUE TITLE
Docs for Visualization API and Logstash are breaking docs build in dev

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#1153]
These errors need to be addressed with new branches built off of `dev`: 

https://readthedocs.org/projects/oss-augur/builds/13140139/

```
/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/checkouts/dev/docs/source/getting-started/command-line-interface/backend.rst:123: WARNING: Error in "code-block" directive:
maximum 1 argument(s) allowed, 11 supplied.

.. code-block:: bash
  # If not specified, defaults to /usr/local/bin/elasticsearch
  $ export ELASTIC_SEARCH_PATH=<path_to_elastic_search_binary>

  # If not specified, defaults to /usr/local/bin/logstash
  $ export LOGSTASH_PATH=<path_to_logstash_binary>

  $ export ROOT_AUGUR_DIRECTORY=<path_to_augur>
/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/checkouts/dev/docs/source/getting-started/command-line-interface/toc.rst:13: WARNING: toctree contains reference to nonexisting document 'getting-started/command-line-interface/run'
/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/checkouts/dev/docs/source/getting-started/command-line-interface/toc.rst:13: WARNING: toctree contains reference to nonexisting document 'getting-started/command-line-interface/configure'
/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/checkouts/dev/docs/source/getting-started/installation.rst:50: WARNING: Title underline too short.

Visualization API calls
----------------------
/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/checkouts/dev/docs/source/getting-started/installation.rst:50: WARNING: Title underline too short.

Visualization API calls
----------------------

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/sphinx/application.py", line 352, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 298, in build_update
    len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 310, in build
    updated_docnames = set(self.read())
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 417, in read
    self._read_serial(docnames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 438, in _read_serial
    self.read_doc(docname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 478, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/sphinx/io.py", line 221, in read_doc
    pub.publish()
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/sphinx/io.py", line 126, in read
    self.parse()
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/docutils/readers/__init__.py", line 77, in parse
    self.parser.parse(self.input, document)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/sphinx/parsers.py", line 104, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2771, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2344, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2356, in explicit_construct
    return method(self, expmatch)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2099, in directive
    directive_class, match, type_name, option_presets)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2148, in run_directive
    result = directive_instance.run()
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/sphinxcontrib/openapi/directive.py", line 55, in run
    spec = _get_spec(abspath, encoding)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/sphinxcontrib/openapi/directive.py", line 23, in _get_spec
    return yaml.safe_load(stream)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/yaml/composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/yaml/parser.py", line 393, in parse_block_sequence_entry
    "expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block collection
  in "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/checkouts/dev/docs/source/rest-api/spec.yml", line 4229, column 8
expected <block end>, but found '<block mapping start>'
  in "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/checkouts/dev/docs/source/rest-api/spec.yml", line 4230, column 9

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/dev/lib/python3.7/site-packages/yaml/parser.py", line 393, in parse_block_sequence_entry
    "expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block collection
  in "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/checkouts/dev/docs/source/rest-api/spec.yml", line 4229, column 8
expected <block end>, but found '<block mapping start>'
  in "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/checkouts/dev/docs/source/rest-api/spec.yml", line 4230, column 9
The full traceback has been saved in /tmp/sphinx-err-rqkpgaez.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

@ABrain7710  & @ivanayov

**Comment by sgoggins** [comment]
@ivanayov and @ABrain7710 : Can you please address these errors (they are well explained in the log messages) ASAP?
1. create a new branch from dev locally `git checkout -b dev-viz-docfix` and `dev-logs-docfix` respectively, make the fixes, and push back to github, then create a PR to merge into `dev`?

Thanks!

**Comment by sgoggins** [comment]
Current build number: https://readthedocs.org/projects/oss-augur/builds/13188633/

Logstash Errors: 
```
eading sources... [ 93%] library-documentation/toc
reading sources... [ 95%] rest-api/api
/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/checkouts/1154/docs/source/development-guide/workers/clustering_worker.rst:57: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/checkouts/1154/docs/source/development-guide/workers/discourse_analysis_worker.rst:16: WARNING: undecodable source characters, replacing with "?": b'Structured prediction is a type of supervised machine learning technique that involves predicting a structured group of multiple correlated outputs at the same time. In the problem of discourse act classification, it means predicting discourse labels for each utterance in a discourse sequence simultaneously. Structured prediction methods take advantage of the inherent dependency among the sentences in a discussion thread. One of the popular methods in structured prediction problem is >>>\x91<<<Conditional Random Fields\x92 (CRF). They belong to a class of undirected graphical models where each node represents a random variable and edge denotes dependency among the connected random variables. In CRF, the nodes are divided into two distinct sets - input features \x91X\x92 (also called an observed variable)and output labels \x91Y\x92. We can then model the conditional distribution p(Y | X) using maximum likelihood learning of parameters. The optimization problem is often convex and can be solved using a gradient descent algorithm like lbfgs. In case of discourse anlaysis, each message is dependent on the preceding and succeeding messages giving rise to the linear chain-like structure.'
/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/checkouts/1154/docs/source/development-guide/workers/discourse_analysis_worker.rst:16: WARNING: undecodable source characters, replacing with "?": b'Structured prediction is a type of supervised machine learning technique that involves predicting a structured group of multiple correlated outputs at the same time. In the problem of discourse act classification, it means predicting discourse labels for each utterance in a discourse sequence simultaneously. Structured prediction methods take advantage of the inherent dependency among the sentences in a discussion thread. One of the popular methods in structured prediction problem is \x91Conditional Random Fields>>>\x92<<< (CRF). They belong to a class of undirected graphical models where each node represents a random variable and edge denotes dependency among the connected random variables. In CRF, the nodes are divided into two distinct sets - input features \x91X\x92 (also called an observed variable)and output labels \x91Y\x92. We can then model the conditional distribution p(Y | X) using maximum likelihood learning of parameters. The optimization problem is often convex and can be solved using a gradient descent algorithm like lbfgs. In case of discourse anlaysis, each message is dependent on the preceding and succeeding messages giving rise to the linear chain-like structure.'
/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/checkouts/1154/docs/source/development-guide/workers/discourse_analysis_worker.rst:16: WARNING: undecodable source characters, replacing with "?": b'Structured prediction is a type of supervised machine learning technique that involves predicting a structured group of multiple correlated outputs at the same time. In the problem of discourse act classification, it means predicting discourse labels for each utterance in a discourse sequence simultaneously. Structured prediction methods take advantage of the inherent dependency among the sentences in a discussion thread. One of the popular methods in structured prediction problem is \x91Conditional Random Fields\x92 (CRF). They belong to a class of undirected graphical models where each node represents a random variable and edge denotes dependency among the connected random variables. In CRF, the nodes are divided into two distinct sets - input features >>>\x91<<<X\x92 (also called an observed variable)and output labels \x91Y\x92. We can then model the conditional distribution p(Y | X) using maximum likelihood learning of parameters. The optimization problem is often convex and can be solved using a gradient descent algorithm like lbfgs. In case of discourse anlaysis, each message is dependent on the preceding and succeeding messages giving rise to the linear chain-like structure.'
/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/checkouts/1154/docs/source/development-guide/workers/discourse_analysis_worker.rst:16: WARNING: undecodable source characters, replacing with "?": b'Structured prediction is a type of supervised machine learning technique that involves predicting a structured group of multiple correlated outputs at the same time. In the problem of discourse act classification, it means predicting discourse labels for each utterance in a discourse sequence simultaneously. Structured prediction methods take advantage of the inherent dependency among the sentences in a discussion thread. One of the popular methods in structured prediction problem is \x91Conditional Random Fields\x92 (CRF). They belong to a class of undirected graphical models where each node represents a random variable and edge denotes dependency among the connected random variables. In CRF, the nodes are divided into two distinct sets - input features \x91X>>>\x92<<< (also called an observed variable)and output labels \x91Y\x92. We can then model the conditional distribution p(Y | X) using maximum likelihood learning of parameters. The optimization problem is often convex and can be solved using a gradient descent algorithm like lbfgs. In case of discourse anlaysis, each message is dependent on the preceding and succeeding messages giving rise to the linear chain-like structure.'
/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/checkouts/1154/docs/source/development-guide/workers/discourse_analysis_worker.rst:16: WARNING: undecodable source characters, replacing with "?": b'Structured prediction is a type of supervised machine learning technique that involves predicting a structured group of multiple correlated outputs at the same time. In the problem of discourse act classification, it means predicting discourse labels for each utterance in a discourse sequence simultaneously. Structured prediction methods take advantage of the inherent dependency among the sentences in a discussion thread. One of the popular methods in structured prediction problem is \x91Conditional Random Fields\x92 (CRF). They belong to a class of undirected graphical models where each node represents a random variable and edge denotes dependency among the connected random variables. In CRF, the nodes are divided into two distinct sets - input features \x91X\x92 (also called an observed variable)and output labels >>>\x91<<<Y\x92. We can then model the conditional distribution p(Y | X) using maximum likelihood learning of parameters. The optimization problem is often convex and can be solved using a gradient descent algorithm like lbfgs. In case of discourse anlaysis, each message is dependent on the preceding and succeeding messages giving rise to the linear chain-like structure.'
/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/checkouts/1154/docs/source/development-guide/workers/discourse_analysis_worker.rst:16: WARNING: undecodable source characters, replacing with "?": b'Structured prediction is a type of supervised machine learning technique that involves predicting a structured group of multiple correlated outputs at the same time. In the problem of discourse act classification, it means predicting discourse labels for each utterance in a discourse sequence simultaneously. Structured prediction methods take advantage of the inherent dependency among the sentences in a discussion thread. One of the popular methods in structured prediction problem is \x91Conditional Random Fields\x92 (CRF). They belong to a class of undirected graphical models where each node represents a random variable and edge denotes dependency among the connected random variables. In CRF, the nodes are divided into two distinct sets - input features \x91X\x92 (also called an observed variable)and output labels \x91Y>>>\x92<<<. We can then model the conditional distribution p(Y | X) using maximum likelihood learning of parameters. The optimization problem is often convex and can be solved using a gradient descent algorithm like lbfgs. In case of discourse anlaysis, each message is dependent on the preceding and succeeding messages giving rise to the linear chain-like structure.'
/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/checkouts/1154/docs/source/getting-started/command-line-interface/backend.rst:123: WARNING: Error in "code-block" directive:
maximum 1 argument(s) allowed, 11 supplied.

.. code-block:: bash
  # If not specified, defaults to /usr/local/bin/elasticsearch
  $ export ELASTIC_SEARCH_PATH=<path_to_elastic_search_binary>

  # If not specified, defaults to /usr/local/bin/logstash
  $ export LOGSTASH_PATH=<path_to_logstash_binary>

  $ export ROOT_AUGUR_DIRECTORY=<path_to_augur>
/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/checkouts/1154/docs/source/getting-started/command-line-interface/toc.rst:13: WARNING: toctree contains reference to nonexisting document 'getting-started/command-line-interface/run'
/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/checkouts/1154/docs/source/getting-started/command-line-interface/toc.rst:13: WARNING: toctree contains reference to nonexisting document 'getting-started/command-line-interface/configure'
/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/checkouts/1154/docs/source/getting-started/installation.rst:50: WARNING: Title underline too short.
```

Visualization API Doc Errors: 
```
Visualization API calls
----------------------
/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/checkouts/1154/docs/source/getting-started/installation.rst:50: WARNING: Title underline too short.

Visualization API calls
----------------------

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/sphinx/application.py", line 352, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 298, in build_update
    len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 310, in build
    updated_docnames = set(self.read())
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 417, in read
    self._read_serial(docnames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 438, in _read_serial
    self.read_doc(docname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 478, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/sphinx/io.py", line 221, in read_doc
    pub.publish()
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/sphinx/io.py", line 126, in read
    self.parse()
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/docutils/readers/__init__.py", line 77, in parse
    self.parser.parse(self.input, document)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/sphinx/parsers.py", line 104, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2771, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2344, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2356, in explicit_construct
    return method(self, expmatch)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2099, in directive
    directive_class, match, type_name, option_presets)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2148, in run_directive
    result = directive_instance.run()
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/sphinxcontrib/openapi/directive.py", line 55, in run
    spec = _get_spec(abspath, encoding)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/sphinxcontrib/openapi/directive.py", line 23, in _get_spec
    return yaml.safe_load(stream)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/yaml/composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/yaml/parser.py", line 393, in parse_block_sequence_entry
    "expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block collection
  in "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/checkouts/1154/docs/source/rest-api/spec.yml", line 4229, column 8
expected <block end>, but found '<block mapping start>'
  in "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/checkouts/1154/docs/source/rest-api/spec.yml", line 4230, column 9

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/envs/1154/lib/python3.7/site-packages/yaml/parser.py", line 393, in parse_block_sequence_entry
    "expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block collection
  in "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/checkouts/1154/docs/source/rest-api/spec.yml", line 4229, column 8
expected <block end>, but found '<block mapping start>'
  in "/home/docs/checkouts/readthedocs.org/user_builds/oss-augur/checkouts/1154/docs/source/rest-api/spec.yml", line 4230, column 9
The full traceback has been saved in /tmp/sphinx-err-1vzwv8yu.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. 
```

- [ ] Fix Viz api docs
- [ ] Fix logstash docs

Thanks!

**Comment by sgoggins** [comment]
@ivanayov and @ABrain7710 : Can you please address these errors (they are well explained in the log messages) ASAP?

    create a new branch from dev locally git checkout -b dev-viz-docfix and dev-logs-docfix respectively, make the fixes, and push back to github, then create a PR to merge into dev?

Thanks!

**Comment by sgoggins** [comment]
@ivanayov and @ABrain7710 : Here's how I create and push a branch like above: 
```
gogginsS@DJ-At-The-End-Of-The-World chaoss % git clone https://github.com/chaoss/augur docs-fix-general
Cloning into 'docs-fix-general'...
remote: Enumerating objects: 121, done.
remote: Counting objects: 100% (121/121), done.
remote: Compressing objects: 100% (95/95), done.
remote: Total 38803 (delta 57), reused 59 (delta 26), pack-reused 38682
Receiving objects: 100% (38803/38803), 161.72 MiB | 20.87 MiB/s, done.
Resolving deltas: 100% (26660/26660), done.
gogginsS@DJ-At-The-End-Of-The-World chaoss % cd docs-fix-general 
gogginsS@DJ-At-The-End-Of-The-World docs-fix-general % git checkout -b docs-fix-general
Switched to a new branch 'docs-fix-general'
gogginsS@DJ-At-The-End-Of-The-World docs-fix-general % git push
fatal: The current branch docs-fix-general has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin docs-fix-general

gogginsS@DJ-At-The-End-Of-The-World docs-fix-general %  git push --set-upstream origin docs-fix-general
Total 0 (delta 0), reused 0 (delta 0)
remote: 
remote: Create a pull request for 'docs-fix-general' on GitHub by visiting:
remote:      https://github.com/chaoss/augur/pull/new/docs-fix-general
remote: 
To https://github.com/chaoss/augur
 * [new branch]        docs-fix-general -> docs-fix-general
Branch 'docs-fix-general' set up to track remote branch 'docs-fix-general' from 'origin'.
```

Then, once I change something, I push.  When I'm done, PR!

You can test locally with `make docs`

**Comment by ABrain7710** [comment]
@sgoggins I'm not seeing where to view the error messages after I build it with `make docs`

**Comment by sgoggins** [comment]
This is fixed!
