### ISSUE TITLE
Database initialization fails for 0.17.0 Augur container

### ISSUE THREAD

**Issue by jberkus** [chaoss/augur#1354]
**Description:**

0.17.0 now relies on having "psql" on the command line for database initialization.  Not only is this not great practice, the Dockerfile for that version does not include the installation of psql, so db initialization fails.

**How to reproduce:**
1. Checkout current master
2. Build a new container image using the backend dockerfile
3. Run the container image as such: `podman run -it --env-file=docker_env --entrypoint=/bin/bash localhost/augurlabs/augur-backend:2`
4. Get the following error:

```
FileNotFoundError: [Errno 2] No such file or directory: 'psql'
```

**Expected behavior:**

The database should have initialized, preferably by using commands send through SQLAlchemy, not shelling out to psql.

**Log files**

```
root@d842eeec5393:/augur# augur db create-schema
2021-07-16 19:38:41,303ms [PID: 130] augur.logging [DEBUG] Logfiles initialized at /augur/logs/
2021-07-16 19:38:41,303ms [PID: 130] augur.application [DEBUG] Running in online mode
2021-07-16 19:38:41,334ms [PID: 130] augur.application [DEBUG] Database connection successfully established
2021-07-16 19:38:41,334ms [PID: 130] augur.metrics [DEBUG] Importing metrics
CLI: [db.check_pgpass_credentials] [INFO] ~/.pgpass does not exist, creating.
CLI: [db.check_pgpass_credentials] [INFO] Adding credentials to $HOME/.pgpass
Traceback (most recent call last):
  File "/usr/local/bin/augur", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/augur/cli/__init__.py", line 13, in new_func
    return ctx.invoke(f, ctx.obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/augur/cli/db.py", line 214, in create_schema
    run_psql_command_in_database(augur_app, '-f', 'schema/create_schema.sql')
  File "/usr/local/lib/python3.8/site-packages/augur/cli/db.py", line 296, in run_psql_command_in_database
    call(['psql', '-h', augur_app.config.get_value('Database', 'host'),\
  File "/usr/local/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'psql'

```

**Software versions:**
 - Augur: 0.17.0
 - OS: Container image

**Comment by sgoggins** [comment]
Thanks, @jberkus ... Oy. Fixing.
