### ISSUE TITLE
A error when install augur.

### ISSUE THREAD

**Issue by yodayuuki55** [chaoss/augur#1456]
The following is my error after `make install`:

> Processing /root/augur
Collecting Beaker==1.11.0 (from augur==0.20.4)
  Using cached https://files.pythonhosted.org/packages/04/7b/a3eb9939d931a55c69e4bcaa82dbc64f6df9612c374e782f4ab3c176910e/Beaker-1.11.0.tar.gz
Collecting Flask-Cors==3.0.10 (from augur==0.20.4)
  Using cached https://files.pythonhosted.org/packages/db/84/901e700de86604b1c4ef4b57110d4e947c218b9997adf5d38fa7da493bce/Flask_Cors-3.0.10-py2.py3-none-any.whl
Collecting Flask-Login==0.5.0 (from augur==0.20.4)
  Using cached https://files.pythonhosted.org/packages/2b/83/ac5bf3279f969704fc1e63f050c50e10985e50fd340e6069ec7e09df5442/Flask_Login-0.5.0-py2.py3-none-any.whl
Collecting Flask-WTF==0.14.3 (from augur==0.20.4)
  Using cached https://files.pythonhosted.org/packages/36/a9/8c01171066bd7a524ee005d81bb4a8aa446ab178043a1ad6cb5dc8f0bd83/Flask_WTF-0.14.3-py2.py3-none-any.whl
Collecting Flask==1.1.4 (from augur==0.20.4)
  Using cached https://files.pythonhosted.org/packages/e8/6d/994208daa354f68fd89a34a8bafbeaab26fda84e7af1e35bdaed02b667e6/Flask-1.1.4-py2.py3-none-any.whl
Collecting Jinja2<3.0,>=2.10.1 (from augur==0.20.4)
  Using cached https://files.pythonhosted.org/packages/7e/c2/1eece8c95ddbc9b1aeb64f5783a9e07a286de42191b7204d67b7496ddf35/Jinja2-2.11.3-py2.py3-none-any.whl
Collecting SQLAlchemy==1.3.23 (from augur==0.20.4)
  Using cached https://files.pythonhosted.org/packages/41/b2/91fa9844a056ce3e67a028ce44fab07ea5fde399382a9216c6c28b7072f9/SQLAlchemy-1.3.23-cp36-cp36m-manylinux1_x86_64.whl
Collecting blinker==1.4 (from augur==0.20.4)
  Using cached https://files.pythonhosted.org/packages/1b/51/e2a9f3b757eb802f61dc1f2b09c8c99f6eb01cf06416c0671253536517b6/blinker-1.4.tar.gz
Collecting bokeh==2.0.2 (from augur==0.20.4)
  Using cached https://files.pythonhosted.org/packages/30/cf/9bef843880084b646cf5e6988e8f0aa081dccdf09f1617cfc6755f9a3353/bokeh-2.0.2.tar.gz
Collecting boto3==1.17.57 (from augur==0.20.4)
  Using cached https://files.pythonhosted.org/packages/9b/e5/96f7156e6ebf7ab992471479c3c55f0be2f31360fcdcac21aa6f782c036a/boto3-1.17.57-py2.py3-none-any.whl
Collecting click<8.0,>=5.1 (from augur==0.20.4)
  Using cached https://files.pythonhosted.org/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl
Collecting cloudpickle>=0.2.2 (from augur==0.20.4)
  Using cached https://files.pythonhosted.org/packages/e7/e3/898487e5dbeb612054cf2e0c188463acb358167fef749c53c8bb8918cea1/cloudpickle-1.6.0-py3-none-any.whl
Collecting coloredlogs==15.0 (from augur==0.20.4)
  Using cached https://files.pythonhosted.org/packages/84/a6/837dbf6eac344cb74f0ba86b79e8180855570af3e26bcb1ea5f650cf944c/coloredlogs-15.0-py2.py3-none-any.whl
Collecting dask>=2021.6.2 (from augur==0.20.4)
  Could not find a version that satisfies the requirement dask>=2021.6.2 (from augur==0.20.4) (from versions: 0.7.4.linux-x86_64, 0.7.5.linux-x86_64, 0.7.6.linux-x86_64, 0.8.1.macosx-10.5-x86_64, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.3.0, 0.4.0, 0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.8.0, 0.8.1, 0.8.2, 0.9.0, 0.10.0, 0.10.1, 0.10.2, 0.11.0, 0.11.1, 0.12.0, 0.13.0rc1, 0.13.0, 0.14.0, 0.14.1, 0.14.2, 0.14.3, 0.15.0, 0.15.1, 0.15.2, 0.15.3, 0.15.4, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.17.2, 0.17.3, 0.17.4, 0.17.5, 0.18.0, 0.18.1, 0.18.2, 0.19.0, 0.19.1, 0.19.2, 0.19.3, 0.19.4, 0.20.0, 0.20.1, 0.20.2, 1.0.0, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.2.0, 1.2.1, 1.2.2, 2.0.0, 2.1.0, 2.2.0, 2.3.0, 2.4.0, 2.5.0, 2.5.2, 2.6.0, 2.7.0, 2.8.0, 2.8.1, 2.9.0, 2.9.1, 2.9.2, 2.10.0, 2.10.1, 2.11.0, 2.12.0, 2.13.0, 2.14.0, 2.15.0, 2.16.0, 2.17.0, 2.17.1, 2.17.2, 2.18.0, 2.18.1, 2.19.0, 2.20.0, 2.21.0, 2.22.0, 2.23.0, 2.24.0, 2.25.0, 2.26.0, 2.27.0, 2.28.0, 2.29.0, 2.30.0, 2020.12.0, 2021.1.0, 2021.1.1, 2021.2.0, 2021.3.0)
No matching distribution found for dask>=2021.6.2 (from augur==0.20.4)
Makefile:34: recipe for target 'install' failed
make: *** [install] Error 1

**Comment by yodayuuki55** [comment]
okay,i solved it,but there is a new error:

> Exception:
Traceback (most recent call last):
  File "/root/.virtualenvs/augur_env/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/response.py", line 302, in _error_catcher
    yield
  File "/root/.virtualenvs/augur_env/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/response.py", line 384, in read
    data = self._fp.read(amt)
  File "/root/.virtualenvs/augur_env/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/filewrapper.py", line 60, in read
    data = self.__fp.read(amt)
  File "/usr/lib/python3.7/http/client.py", line 457, in read
    n = self.readinto(b)
  File "/usr/lib/python3.7/http/client.py", line 501, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/download.py", line 902, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/download.py", line 603, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/utils/hashes.py", line 46, in check_against_chunks
    for chunk in chunks:
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/download.py", line 571, in written_chunks
    for chunk in chunks:
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/utils/ui.py", line 139, in iter
    for x in it:
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/download.py", line 560, in resp_read
    decode_content=False):
  File "/root/.virtualenvs/augur_env/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/response.py", line 436, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/root/.virtualenvs/augur_env/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/response.py", line 401, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/root/.virtualenvs/augur_env/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/response.py", line 307, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
Makefile:34: recipe for target 'install' failed
make: *** [install] Error 2

**Comment by yodayuuki55** [comment]
>   Downloading gensim-3.8.3-cp37-cp37m-manylinux1_x86_64.whl (24.2 MB)
ERROR: Exception:
Traceback (most recent call last):
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "/usr/lib/python3.7/http/client.py", line 457, in read
    n = self.readinto(b)
  File "/usr/lib/python3.7/http/client.py", line 501, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 173, in _main
    status = self.run(options, args)
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 316, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
    collected.requirements, max_rounds=try_to_avoid_resolution_too_deep
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 472, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 366, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 212, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 203, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 140, in __bool__
    return any(self)
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 128, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 32, in _iter_built
    candidate = func()
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 209, in _make_candidate_from_link
    version=version,
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 301, in __init__
    version=version,
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 227, in _prepare
    dist = self._prepare_distribution()
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 306, in _prepare_distribution
    self._ireq, parallel_builds=True
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 508, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 552, in _prepare_linked_requirement
    self.download_dir, hashes
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 243, in unpack_url
    hashes=hashes,
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 102, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/_internal/network/download.py", line 145, in __call__
    for chunk in chunks:
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/_internal/cli/progress_bars.py", line 144, in iter
    for x in it:
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/_internal/network/utils.py", line 87, in response_chunks
    decode_content=False,
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 541, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
Makefile:34: recipe for target 'install' failed
make: *** [install] Error 2

**Comment by yodayuuki55** [comment]
When i choose 'no',there is a new error:

> Would you like to install Augur's frontend dependencies? [Y/n] n
Skipping frontend dependencies...
Traceback (most recent call last):
  File "/root/.virtualenvs/augur_env/bin/augur", line 8, in <module>
    sys.exit(run())
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/augur/cli/__init__.py", line 12, in new_func
    ctx.obj = Application()
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/augur/application.py", line 62, in __init__
    self.database, self.operations_database, self.spdx_database = self._connect_to_database()
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/augur/application.py", line 79, in _connect_to_database
    connect_args={'options': f'-csearch_path={csearch_path_options}'}, pool_pre_ping=True)
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/sqlalchemy/engine/__init__.py", line 520, in create_engine
    return strategy.create(*args, **kwargs)
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 54, in create
    u = url.make_url(name_or_url)
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 229, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 288, in _parse_rfc1738_args
    return URL(name, **components)
  File "/root/.virtualenvs/augur_env/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 71, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: ''
Makefile:34: recipe for target 'install' failed
make: *** [install] Error 1

**Comment by sgoggins** [comment]
@yodayuuki55 : What platform are you installing on? The first error that you solved suggests the package manager for your OS may not be current. The second error collection is, unfortunately, "normal" for our frontend installation now. 

The final error you posted suggests that your database schema was not properly installed. Can you verify that there is an `augur_data` and `augur_operations` schema with tables in the database? 

If there is not, delete the `augur.config.json` file, and try `make install-dev`

**Comment by yodayuuki55** [comment]
@sgoggins Thanks for reply! I wiil try to solve the second error later. 

For the final error, could you tell me how to look for `augur_data` and `augur_operations` schema in detail? I used command `find` but i cant see them.

AND i tried `make install-dev` after deleting `augur.config.json`,there is the same error as the final.

**Comment by sgoggins** [comment]
@yodayuuki55 : Sorry for the long delay in responding. 

Augur knows how to find the schemas. Errors like the ones you are seeing I have only encountered when my Python virtual environment is messed up. 

Try this: 
1. Create a new python virtual environment `python3 -m venv {path}/newvenv`
2. Assuming you have an `augur.config.json` again, do a `make rebuild-dev`

**Comment by yodayuuki55** [comment]
@sgoggins Sorry for delay due to my other work.
Today,i retried it and there is a new error:

> Traceback (most recent call last):
  File "/home/sibo/.virtualenvs/augur_env/bin/augur", line 33, in <module>
    sys.exit(load_entry_point('augur', 'console_scripts', 'augur')())
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/sibo/augur/augur/cli/__init__.py", line 12, in new_func
    ctx.obj = Application()
  File "/home/sibo/augur/augur/application.py", line 62, in __init__
    self.database, self.operations_database, self.spdx_database = self._connect_to_database()
  File "/home/sibo/augur/augur/application.py", line 96, in _connect_to_database
    raise(e)
  File "/home/sibo/augur/augur/application.py", line 89, in _connect_to_database
    engine.connect().close()
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2263, in connect
    return self._connection_cls(self, **kwargs)
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 104, in __init__
    else engine.raw_connection()
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2370, in raw_connection
    self.pool.unique_connection, _connection
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2340, in _wrap_pool_connect
    e, dialect, self
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1584, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 304, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 241, in _do_get
    return self._create_connection()
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 508, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "Augur"
FATAL:  password authentication failed for user "Augur

I am sure that i put in correct password.

**Comment by yodayuuki55** [comment]
> The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sibo/.virtualenvs/augur_env/bin/augur", line 8, in <module>
    sys.exit(run())
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/augur/cli/__init__.py", line 13, in new_func
    return ctx.invoke(f, ctx.obj, *args, **kwargs)
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/augur/cli/db.py", line 255, in get_api_key
    print(augur_app.database.execute(get_api_key_sql).fetchone()[0])
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2235, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "augur_operations.augur_settings" does not exist
LINE 2:         SELECT value FROM augur_operations.augur_settings WH...
                                  ^

[SQL:
        SELECT value FROM augur_operations.augur_settings WHERE setting='augur_api_key';
    ]
(Background on this error at: http://sqlalche.me/e/13/f405)
Makefile:34: recipe for target 'install' failed
make: *** [install] Error 1
