### ISSUE TITLE
Errors when setting up database credentials

### ISSUE THREAD

**Issue by yodayuuki55** [chaoss/augur#1517]
After inputing all information,it told me `password authentication failed for user`:
> Generating configuration file...
CLI: [config.init] [INFO] Config written to /home/sibo/augur/augur.config.json
CLI: [config.init_frontend] [INFO] Config written to /home/sibo/augur/frontend/frontend.config.json
CLI: [db.check_pgpass_credentials] [INFO] Credentials found in $HOME/.pgpass
psql: error: connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "augur"
password retrieved from file "/home/sibo/.pgpass"
connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "augur"
password retrieved from file "/home/sibo/.pgpass"
psql: error: connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "augur"
password retrieved from file "/home/sibo/.pgpass"
connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "augur"
password retrieved from file "/home/sibo/.pgpass"
psql: error: connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "augur"
password retrieved from file "/home/sibo/.pgpass"
connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "augur"
password retrieved from file "/home/sibo/.pgpass"
psql: error: connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "augur"
password retrieved from file "/home/sibo/.pgpass"
connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "augur"
password retrieved from file "/home/sibo/.pgpass"
CLI: [db.check_pgpass_credentials] [INFO] Credentials found in $HOME/.pgpass
psql: error: connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "augur"
password retrieved from file "/home/sibo/.pgpass"
connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "augur"
password retrieved from file "/home/sibo/.pgpass"

The second error:

> Traceback (most recent call last):
  File "/home/sibo/.virtualenvs/augur_env/bin/augur", line 33, in <module>
    sys.exit(load_entry_point('augur', 'console_scripts', 'augur')())
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/sibo/augur/augur/cli/__init__.py", line 13, in new_func
    return ctx.invoke(f, ctx.obj, *args, **kwargs)
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/sibo/augur/augur/cli/db.py", line 255, in get_api_key
    print(augur_app.database.execute(get_api_key_sql).fetchone()[0])
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2235, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/sibo/.virtualenvs/augur_env/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "augur_operations.augur_settings" does not exist
LINE 2:         SELECT value FROM augur_operations.augur_settings WH...
                                  ^
[SQL:
        SELECT value FROM augur_operations.augur_settings WHERE setting='augur_api_key';
    ]
(Background on this error at: http://sqlalche.me/e/13/f405)
Makefile:37: recipe for target 'install-dev' failed

**Comment by sgoggins** [comment]
This error typically occurs when you enter the wrong username or password when prompted during setup. The fix is to edit the information in the Database block of the generated `augur.config.json`
