### ISSUE TITLE
Fresh install on Amazon AMI Issue with make install-dev

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#163]
Getting a few of these hairy messages. Please advise. It ultimately works. 

Installing collected packages: cython, six, protobuf, scandir, pathlib2, pickleshare, backports.shutil-get-terminal-size, wcwidth, prompt-toolkit, ipython-genutils, decorator, enum34, traitlets, ptyprocess, pexpect, simplegeneric, pygments, ipython, ipdb, setuptools-git, beautifulsoup4, itsdangerous, MarkupSafe, Jinja2, Werkzeug, click, flask, flask-cors, asn1crypto, pycparser, cffi, idna, ipaddress, cryptography, PyMySQL, sqlalchemy, numpy, pytz, pandas, attrs, pluggy, funcsigs, atomicwrites, more-itertools, py, pytest, pyjwt, PyGithub, smmap2, gitdb2, GitPython, gunicorn, monotonic, humanfriendly, coloredlogs, requests-file, tldextract, beaker, augur
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/usr/lib64/python2.7/shutil.py", line 97, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/usr/local/lib64/python2.7/site-packages/cython.py'
You are using pip version 9.0.3, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
/usr/bin/python: No module named ipykernel

**Comment by ccarterlandis** [comment]
Does using `sudo make install-dev` give the same issues?

**Comment by howderek** [comment]
users should not need root permissions to install Augur

**Comment by howderek** [comment]
I suspect that Anaconda is not being activated properly on `make install-dev` because it looks like Python 2.7 is being used
