### ISSUE TITLE
"html" module needed manually installed

### ISSUE THREAD

**Issue by Nebrethar** [chaoss/augur#174]
**Describe the bug**
I am in the process of installing augur on a clean VM and ran into an issue. 
```
Traceback (most recent call last):
  File "/usr/local/bin/augur", line 11, in <module>
    load_entry_point('augur', 'console_scripts', 'augur')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2714, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2332, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2338, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/nebrethar/augur/augur/runtime.py", line 14, in <module>
    from augur.server import Server
  File "/home/nebrethar/augur/augur/server.py", line 9, in <module>
    import html
ImportError: No module named html
```
I ran `pip install html` to get past the bug.

**To Reproduce**
1. Follow all installation instructions on a PC like my VM.

**Expected behavior**
I expected Augur to run like normal.

**Screenshots**
I covered all that would be seen with the code.

**Desktop (please complete the following information):**
 - OS: Ubuntu 64
 - Browser: None
 - Version: 18.04 LTS

**Comment by howderek** [comment]
Hi @Nebrethar, we only support Python 3, which I suspect is the issue. We will make this more clear in our docs.

**Comment by howderek** [comment]
@Nebrethar which directions were you using to install?

**Comment by Nebrethar** [comment]
@howderek 
I used Ubuntu installation instructions and Augur installation instructions that followed.

https://github.com/OSSHealth/augur/blob/master/docs/dev-install.md

I've been running into a few errors, including multiprocessor, that indicate that I am running python 2.7 or so.

When I type python with or without the augur env, I get 3.6 for my py version. I was not able to complete the install today.

**Comment by howderek** [comment]
Resolved during consultation with @Nebrethar
