### ISSUE TITLE
Broken install / runtime since recent commit

### ISSUE THREAD

**Issue by Nebrethar** [chaoss/augur#194]
I've had this issue a couple times during installs in the past couple of days.

```
Traceback (most recent call last):
  File "/usr/local/bin/augur", line 11, in <module>
    load_entry_point('augur', 'console_scripts', 'augur')()
  File "/home/msnell/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/msnell/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/home/msnell/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/home/msnell/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/msnell/augur/augur/__init__.py", line 10, in <module>
    from .application import Application
  File "/home/msnell/augur/augur/application.py", line 22, in <module>
    import augur.plugins.core
ModuleNotFoundError: No module named 'augur.plugins.core'
```

I was able to checkout to 0a46d5e (changed hover colors for repo compare select, reset button collapses … ) and it worked like normal. Anything after that has caused problems for me.

I am running Ubuntu 18.04 Desktop, the latest version on a desktop machine.

**Comment by Nebrethar** [comment]
Fixed with revert, thanks.
