### ISSUE TITLE
Repo with a private URL or behind a VPN causes housekeeper process to hang

### ISSUE THREAD

**Issue by ignacioherdez** [chaoss/augur#2027]
**Description:**
If you add a repo that Augur has no access, which could have been added to the DB by mistake by the user when adding test repos to the database.

I have been troubleshooting this for a long while and turns out to be that there were multiple repos in the **augur_data.repo** table that were private and could only be accessed behind a VPN.

Setting **Logging**  to debug in the augur.config.json file did not do much as it just gave logs prior the housekeeper job and it hung while it booted housekeeper.

**How I found where the issue lied**
- In **augur.config.json** under housekeeper config section changed the update_redirects switch from 0 to 1 and I ran augur backend service which gave me the following error on the screen: 

```
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/augur_env/bin/augur", line 8, in <module>
    sys.exit(run())
  File "/home/ubuntu/.virtualenvs/augur_env/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.virtualenvs/augur_env/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.virtualenvs/augur_env/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.virtualenvs/augur_env/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.virtualenvs/augur_env/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.virtualenvs/augur_env/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/.virtualenvs/augur_env/lib/python3.10/site-packages/augur/cli/backend.py", line 60, in start
    master = initialize_components(augur_app, disable_housekeeper)
  File "/home/ubuntu/.virtualenvs/augur_env/lib/python3.10/site-packages/augur/cli/backend.py", line 164, in initialize_components
    housekeeper = Housekeeper(broker=broker, augur_app=augur_app)
  File "/home/ubuntu/.virtualenvs/augur_env/lib/python3.10/site-packages/augur/housekeeper.py", line 53, in __init__
    self.update_url_redirects()
  File "/home/ubuntu/.virtualenvs/augur_env/lib/python3.10/site-packages/augur/housekeeper.py", line 345, in update_url_redirects
    r = requests.get(url, timeout=(4.44, 7.01))
  File "/home/ubuntu/.virtualenvs/augur_env/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/ubuntu/.virtualenvs/augur_env/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ubuntu/.virtualenvs/augur_env/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ubuntu/.virtualenvs/augur_env/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/ubuntu/.virtualenvs/augur_env/lib/python3.10/site-packages/requests/adapters.py", line 553, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='code.private.host.com', port=443): Max retries exceeded with url: /category/repo-name (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f005b3ab820>, 'Connection to code.private.host.com timed out. (connect timeout=4.44)'))
```

**How to reproduce:**
1. Adding a non public repo url to Augur DB, any repo that cannot be accessed by the Augur server. 
- code.private.host.com/category/repo-name.git

**Expected behavior:**
```
_augur.housekeeper [INFO] Booting housekeeper_: will hang preparing housekeeper jobs and will not continue the process.
```

**Log files**
This will cause no logs to generate as it will just log:
```
**augur.housekeeper [INFO] Booting housekeeper** 
```

**Software versions:**
 - Augur: 0.42
 - OS: Ubuntu 22.04 LTS
 - Browser: N/A

**How I fixed it:**
1. I gained access to Augur DB and manually removed the repos with inaccessible URLs
2. Deleted the repos by their repo_id 

```
DELETE FROM augur_data.repo
WHERE repo_id = 25452
```
3. Ran Augur backend again and housekeeper managed to move forward with scheduling.

I believe Augur should know whenever a repo url is failing to load or has no access and Max retries exceeded to throw an error to the logs and continue with the rest of the repos in the database instead of just hanging without any helping information.

**Comment by sgoggins** [comment]
@ignacioherdez : Just checking: Did the github token used to access the private repo have privileges to see the private repo? If not, that is probably the issue. If it did have privileges, we will dig deeper.

**Comment by sgoggins** [comment]
@ignacioherdez : Checking back on the token privileges question.
