### ISSUE TITLE
Rare (0.00365% Task Fail Rate) NoneType in Contributor on Large Collection 

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#2052]
Please help us help you by filling out the following sections as thoroughly as you can.

**Description:**
Occurred in Padres database on Flower port 8200. `:8200/task/40492707-2ae3-4ac4-9516-07683b34afea`

Summary Error: 
```
 TypeError("'NoneType' object is not iterable") 
```

Detailed Error:
```
Traceback (most recent call last):
  File "/home/sean/github/virtualenv/k12/lib/python3.8/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/sean/github/virtualenv/k12/lib/python3.8/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/sean/github/rh-augur-new-dev/augur/tasks/github/pull_requests/tasks.py", line 33, in collect_pull_requests
    process_pull_requests(pr_data, f"{owner}/{repo}: Pr task", repo_id, logger)
  File "/home/sean/github/rh-augur-new-dev/augur/tasks/github/pull_requests/tasks.py", line 90, in process_pull_requests
    session.insert_data(contributors, Contributor, ["cntrb_id"])
  File "/home/sean/github/rh-augur-new-dev/augur/application/db/session.py", line 195, in insert_data
    self.insert_data(first_half, natural_keys, return_columns, string_fields, on_conflict_update)
  File "/home/sean/github/rh-augur-new-dev/augur/application/db/session.py", line 119, in insert_data
    data = remove_duplicates_by_uniques(data, natural_keys)
  File "/home/sean/github/rh-augur-new-dev/augur/tasks/util/worker_util.py", line 59, in remove_duplicates_by_uniques
    key = "_".join([str(x[unique]) for unique in uniques])
TypeError: 'NoneType' object is not iterable
```

**Software versions:**
 - Augur: 0.43.1
 - OS: Ubuntu
 - Browser: Clark W. Griswald

**Comment by sgoggins** [comment]
This issue resolved by pull request #2099
