### ISSUE TITLE
Quick Bug: Path Issue on Runtime

### ISSUE THREAD

**Issue by Nebrethar** [chaoss/augur#232]
**Describe the bug:**
This is a quick issue. I was running into a path issue on the dev branch during installation where the path was made with the assumption of the base path in place (i think?). I changed the path at line 14 of metrics_status.py to use a relative link. That could work or a more permanent fix could be found.
Here is the link I put in the old one's place:
```
os.path.dirname(__file__) + "/../../../frontend/app/AugurAPI.js"
```
And here is the full trace:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/nebrethar/augur/augur/runtime.py", line 43, in load
    server = Server()
  File "/home/nebrethar/augur/augur/server.py", line 43, in __init__
    create_plugin_routes(self)
  File "/home/nebrethar/augur/augur/routes/__init__.py", line 8, in create_plugin_routes
    module.create_routes(server)
  File "/home/nebrethar/augur/augur/datasources/metrics_status/__init__.py", line 31, in create_routes
    create_routes(flask_app)
  File "/home/nebrethar/augur/augur/datasources/metrics_status/routes.py", line 19, in create_routes
    metrics_status.create_metrics_status()
  File "/home/nebrethar/augur/augur/datasources/metrics_status/metrics_status.py", line 150, in create_metrics_status
    self.build_implemented_metrics()
  File "/home/nebrethar/augur/augur/datasources/metrics_status/metrics_status.py", line 174, in build_implemented_metrics
    frontend_status_extractor = FrontendStatusExtractor()
  File "/home/nebrethar/augur/augur/datasources/metrics_status/metrics_status.py", line 14, in __init__
    self.api_text = open("/home/nebethar/augur/augur/frontend/app/AugurAPI.js", 'r').read()
FileNotFoundError: [Errno 2] No such file or directory: '/frontend/app/AugurAPI.js'
```

**To Reproduce:**
Install augur with the steps in the installation guide.
Run the command `augur`.

**Expected behavior:**
Augur will run as usual

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04

**Additional context**
I am doing this testing on a fresh install.

**Comment by ccarterlandis** [comment]
I haven't run into this issue before. Is this on `dev` or `risk`?

**Comment by Nebrethar** [comment]
I install dev yesterday and risk today (fresh) and they both had this issue.

**Comment by ccarterlandis** [comment]
I noticed that it seems you're using Python 3.5 to run Augur, would it be possible for you to upgrade to Python 3.6 and test again to see if that fixes anything? I'm not sure how this bug got added, that code hasn't been touched recently.

**Comment by Nebrethar** [comment]
Sorry for the delay. That's a good thing to try. I will be trying a reinstall today with 3.6.

**Comment by Nebrethar** [comment]
It seems like the switch to 3.6 fixed the path issue. Thanks!
