### ISSUE TITLE
Vagrant install issue

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#246]
**Describe the bug:**
When typing "augur" for the first time inside the vagrant box I get this: 

```python
 vagrant@augur:~$ sudo su -
root@augur:~# cd /vagrant/augur/
root@augur:/vagrant/augur# augur
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 834, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (requests 2.9.1 (/usr/lib/python3/dist-packages), Requirement.parse('requests>=2.14.0'), {'PyGithub'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/augur", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 637, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 650, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 834, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (requests 2.9.1 (/usr/lib/python3/dist-packages), Requirement.parse('requests>=2.14.0'), {'PyGithub'}) 
```

**To Reproduce:**
1. Vagrant install in fresh directory
2. Go all the way to typing `augur`

**Expected behavior:**
Rainbows and unicorns

**Desktop (please complete the following information):**
 - OSX
**Additional context**

**Comment by sgoggins** [comment]
actually forgot to `sudo su - ` first on that computer, but the result is the same either way
```python
vagrant@augur:/vagrant/augur$ sudo su -
root@augur:~# ls
vagrant-data
root@augur:~# cd /vagrant/augur
root@augur:/vagrant/augur# augur
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 834, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (requests 2.9.1 (/usr/lib/python3/dist-packages), Requirement.parse('requests>=2.14.0'), {'PyGithub'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/augur", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 637, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 650, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 834, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (requests 2.9.1 (/usr/lib/python3/dist-packages), Requirement.parse('requests>=2.14.0'), {'PyGithub'})
root@augur:/vagrant/augur# 
```

**Comment by ccarterlandis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Vagrant installation issue](https://trello.com/c/KfrUMGgx/20-vagrant-installation-issue)

**Comment by ccarterlandis** [comment]
This issue occurs because the installed version of `requests` was 2.9.1, while the version required by `PyGithub` was 2.14.0 or greater. Running `pip install --upgrade requests` resolved the issue, but there's probably a more stable fix. For now, I'll add a step to the Vagrant provisioning process that updates all installed Python packages, which should cover this case and others should they arise.

**Comment by sgoggins** [comment]
@ccarterlandis : can this be pulled into master before 1pm today?

**Comment by ccarterlandis** [comment]
@sgoggins: I'm about to commit and open a PR into `master`.

**Comment by sgoggins** [comment]
I had to upgrade pip before that worked. FYI.

**Comment by ccarterlandis** [comment]
Pushed documentation update to `hotfix` in [this](https://github.com/chaoss/augur/commit/57f154d94266f9c8a9b331ac9d2dc179e0429d85) commit.

**Comment by sgoggins** [comment]
Actually its not working yet ...

**Comment by sgoggins** [comment]
@ccarterlandis : the new issue is different. closing this one.
