### ISSUE TITLE
code complexity counting task error

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#2538]
**Description:**
This bug does not occur on every collection. It is unclear what the circumstances for generating this error are, but we can see it exists within the padres database. 

**Log files**
```
Traceback (most recent call last):
  File "/home/sean/github/rh-k12/augur/tasks/util/worker_util.py", line 139, in parse_json_from_subprocess_call
    required_output = json.loads(output)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sean/github/virtualenv/rh-k12/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/sean/github/virtualenv/rh-k12/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/sean/github/rh-k12/augur/tasks/git/scc_value_tasks/tasks.py", line 28, in process_scc_value_metrics
    value_model(session,repo_git,repo.repo_id, absolute_repo_path)
  File "/home/sean/github/rh-k12/augur/tasks/git/scc_value_tasks/core.py", line 28, in value_model
    required_output = parse_json_from_subprocess_call(session.logger,['./scc', '-f','json','--by-file', path], cwd=path_to_scc)
  File "/home/sean/github/rh-k12/augur/tasks/util/worker_util.py", line 141, in parse_json_from_subprocess_call
    session.logger.error(f"Could not parse required output! \n output: {output} \n Error: {e}")
NameError: name 'session' is not defined
```

**Software versions:**
 - Augur: Latest version of `dev`
 - OS: Ubuntu 22.x

**Comment by MoralCode** [comment]
The secondary exception about not finding session has been fixed (im looking at the current code and the line is just `logger.error(...`

given the mismatching line numbers betwwn this exception and the current code, id also say the main error has been fixed (wrapped in an if statement it looks like).

not sure about this 100% though.

Recommend closing but leaving open in case im wrong
