### ISSUE TITLE
Docker compose up error

### ISSUE THREAD

**Issue by jiagengliu** [chaoss/augur#2587]
Please help us help you by filling out the following sections as thoroughly as you can.

**Description:**
I'm following the docker installation guide at https://github.com/chaoss/augur/blob/main/docs/new-install.md but encountered an error at the last step when running "sudo docker-compose --env-file ./environment.txt --file docker-compose.yml up"

**Expected behavior:**
augur-0602-augur-1 errors (logs below) and no app is running at localhost:5000 

**Log files**
Note; I'm just listing the error and not including the token part -- I'd suggest not printing the token in the log. 
```
augur-0602-augur-1     | Config created
augur-0602-augur-1     |
augur-0602-augur-1     | /opt/venv/lib/python3.8/site-packages/augur/application/config.py:193: SAWarning: relationship 'Commit.contributor1' will copy column contributors.cntrb_login to column commits.cmt_author_platform_username, which conflicts with relationship(s): 'Commit.contributor' (copies contributors.cntrb_login to commits.cmt_author_platform_username), 'Contributor.commits' (copies contributors.cntrb_login to commits.cmt_author_platform_username). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="commits,contributor"' to the 'Commit.contributor1' relationship. (Background on this warning at: https://sqlalche.me/e/20/qzyx) (This warning originated from the `configure_mappers()` process, which was invoked automatically in response to a user-initiated operation.)
augur-0602-augur-1     |   query = self.session.query(Config).filter(Config.section_name == section_name, Config.setting_name == setting_name)
augur-0602-augur-1     | /opt/venv/lib/python3.8/site-packages/augur/application/config.py:193: SAWarning: relationship 'UserGroup.user' will copy column users.user_id to column user_groups.user_id, which conflicts with relationship(s): 'User.groups' (copies users.user_id to user_groups.user_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="groups"' to the 'UserGroup.user' relationship. (Background on this warning at: https://sqlalche.me/e/20/qzyx) (This warning originated from the `configure_mappers()` process, which was invoked automatically in response to a user-initiated operation.)
augur-0602-augur-1     |   query = self.session.query(Config).filter(Config.section_name == section_name, Config.setting_name == setting_name)
augur-0602-augur-1     | /opt/venv/lib/python3.8/site-packages/augur/application/config.py:193: SAWarning: relationship 'UserRepo.repo' will copy column repo.repo_id to column user_repos.repo_id, which conflicts with relationship(s): 'Repo.user_repo' (copies repo.repo_id to user_repos.repo_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="user_repo"' to the 'UserRepo.repo' relationship. (Background on this warning at: https://sqlalche.me/e/20/qzyx) (This warning originated from the `configure_mappers()` process, which was invoked automatically in response to a user-initiated operation.)
augur-0602-augur-1     |   query = self.session.query(Config).filter(Config.section_name == section_name, Config.setting_name == setting_name)
augur-0602-augur-1     | /opt/venv/lib/python3.8/site-packages/augur/application/config.py:193: SAWarning: relationship 'UserRepo.group' will copy column user_groups.group_id to column user_repos.group_id, which conflicts with relationship(s): 'UserGroup.repos' (copies user_groups.group_id to user_repos.group_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="repos"' to the 'UserRepo.group' relationship. (Background on this warning at: https://sqlalche.me/e/20/qzyx) (This warning originated from the `configure_mappers()` process, which was invoked automatically in response to a user-initiated operation.)
augur-0602-augur-1     |   query = self.session.query(Config).filter(Config.section_name == section_name, Config.setting_name == setting_name)
augur-0602-augur-1     | /opt/venv/lib/python3.8/site-packages/augur/application/config.py:193: SAWarning: relationship 'UserSessionToken.user' will copy column users.user_id to column user_session_tokens.user_id, which conflicts with relationship(s): 'User.tokens' (copies users.user_id to user_session_tokens.user_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="tokens"' to the 'UserSessionToken.user' relationship. (Background on this warning at: https://sqlalche.me/e/20/qzyx) (This warning originated from the `configure_mappers()` process, which was invoked automatically in response to a user-initiated operation.)
augur-0602-augur-1     |   query = self.session.query(Config).filter(Config.section_name == section_name, Config.setting_name == setting_name)
augur-0602-augur-1     | /opt/venv/lib/python3.8/site-packages/augur/application/config.py:193: SAWarning: relationship 'ClientApplication.user' will copy column users.user_id to column client_applications.user_id, which conflicts with relationship(s): 'User.applications' (copies users.user_id to client_applications.user_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="applications"' to the 'ClientApplication.user' relationship. (Background on this warning at: https://sqlalche.me/e/20/qzyx) (This warning originated from the `configure_mappers()` process, which was invoked automatically in response to a user-initiated operation.)
augur-0602-augur-1     |   query = self.session.query(Config).filter(Config.section_name == section_name, Config.setting_name == setting_name)
augur-0602-augur-1     | /opt/venv/lib/python3.8/site-packages/augur/application/config.py:193: SAWarning: relationship 'ClientApplication.sessions' will copy column client_applications.id to column user_session_tokens.application_id, which conflicts with relationship(s): 'UserSessionToken.application' (copies client_applications.id to user_session_tokens.application_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="application"' to the 'ClientApplication.sessions' relationship. (Background on this warning at: https://sqlalche.me/e/20/qzyx) (This warning originated from the `configure_mappers()` process, which was invoked automatically in response to a user-initiated operation.)
augur-0602-augur-1     |   query = self.session.query(Config).filter(Config.section_name == section_name, Config.setting_name == setting_name)
augur-0602-augur-1     | /opt/venv/lib/python3.8/site-packages/augur/application/config.py:193: SAWarning: relationship 'Subscription.application' will copy column client_applications.id to column subscriptions.application_id, which conflicts with relationship(s): 'ClientApplication.subscriptions' (copies client_applications.id to subscriptions.application_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="subscriptions"' to the 'Subscription.application' relationship. (Background on this warning at: https://sqlalche.me/e/20/qzyx) (This warning originated from the `configure_mappers()` process, which was invoked automatically in response to a user-initiated operation.)
augur-0602-augur-1     |   query = self.session.query(Config).filter(Config.section_name == section_name, Config.setting_name == setting_name)
augur-0602-augur-1     | /opt/venv/lib/python3.8/site-packages/augur/application/config.py:193: SAWarning: relationship 'SubscriptionType.subscriptions' will copy column subscription_types.id to column subscriptions.type_id, which conflicts with relationship(s): 'Subscription.type' (copies subscription_types.id to subscriptions.type_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="type"' to the 'SubscriptionType.subscriptions' relationship. (Background on this warning at: https://sqlalche.me/e/20/qzyx) (This warning originated from the `configure_mappers()` process, which was invoked automatically in response to a user-initiated operation.)
augur-0602-augur-1     |   query = self.session.query(Config).filter(Config.section_name == section_name, Config.setting_name == setting_name)
augur-0602-augur-1     | /opt/venv/lib/python3.8/site-packages/augur/application/config.py:193: SAWarning: relationship 'RefreshToken.user_session' will copy column user_session_tokens.token to column refresh_tokens.user_session_token, which conflicts with relationship(s): 'UserSessionToken.refresh_tokens' (copies user_session_tokens.token to refresh_tokens.user_session_token). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="refresh_tokens"' to the 'RefreshToken.user_session' relationship. (Background on this warning at: https://sqlalche.me/e/20/qzyx) (This warning originated from the `configure_mappers()` process, which was invoked automatically in response to a user-initiated operation.)
augur-0602-augur-1     |   query = self.session.query(Config).filter(Config.section_name == section_name, Config.setting_name == setting_name)
augur-0602-augur-1     | Traceback (most recent call last):
augur-0602-augur-1     |   File "/opt/venv/bin/augur", line 8, in <module>
augur-0602-augur-1     |     sys.exit(run())
augur-0602-augur-1     |   File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
augur-0602-augur-1     |     return self.main(*args, **kwargs)
augur-0602-augur-1     |   File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1053, in main
augur-0602-augur-1     |     rv = self.invoke(ctx)
augur-0602-augur-1     |   File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1653, in invoke
augur-0602-augur-1     |     cmd_name, cmd, args = self.resolve_command(ctx, args)
augur-0602-augur-1     |   File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1700, in resolve_command
augur-0602-augur-1     |     cmd = self.get_command(ctx, cmd_name)
augur-0602-augur-1     |   File "/opt/venv/lib/python3.8/site-packages/augur/application/cli/_multicommand.py", line 28, in get_command
augur-0602-augur-1     |     module = importlib.import_module('.' + name, 'augur.application.cli')
augur-0602-augur-1     |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
augur-0602-augur-1     |     return _bootstrap._gcd_import(name[level:], package, level)
augur-0602-augur-1     |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
augur-0602-augur-1     |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
augur-0602-augur-1     |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
augur-0602-augur-1     |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
augur-0602-augur-1     |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
augur-0602-augur-1     |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
augur-0602-augur-1     |   File "/opt/venv/lib/python3.8/site-packages/augur/application/cli/backend.py", line 22, in <module>
augur-0602-augur-1     |     from augur.tasks.start_tasks import augur_collection_monitor, CollectionState, create_collection_status_records
augur-0602-augur-1     |   File "/opt/venv/lib/python3.8/site-packages/augur/tasks/start_tasks.py", line 17, in <module>
augur-0602-augur-1     |     from augur.tasks.github import *
augur-0602-augur-1     |   File "/opt/venv/lib/python3.8/site-packages/augur/tasks/github/__init__.py", line 1, in <module>
augur-0602-augur-1     |     from augur.tasks.github.contributors.tasks import *
augur-0602-augur-1     |   File "/opt/venv/lib/python3.8/site-packages/augur/tasks/github/contributors/tasks.py", line 5, in <module>
augur-0602-augur-1     |     from augur.tasks.init.celery_app import celery_app as celery
augur-0602-augur-1     |   File "/opt/venv/lib/python3.8/site-packages/augur/tasks/init/celery_app.py", line 74, in <module>
augur-0602-augur-1     |     redis_db_number, redis_conn_string = get_redis_conn_values()
augur-0602-augur-1     |   File "/opt/venv/lib/python3.8/site-packages/augur/tasks/init/__init__.py", line 15, in get_redis_conn_values
augur-0602-augur-1     |     redis_db_number = config.get_value("Redis", "cache_group") * 3
augur-0602-augur-1     | TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```

**Software versions:**
 - Augur: N/A
 - OS: Ubuntu 22.04.3 LTS
 - Browser: N/A

**Comment by sgoggins** [comment]
@Ulincsys : can you reexamine our docker compose and see if we have something we can do to increase its .. working-ness?

**Comment by Ulincsys** [comment]
Definitely, I will look over our Docker configuration to make sure everything's in order, and to see where improvements can be made.

The Docker compose configuration has been updated a few times since this issue was posted, but I'm not sure that this issue specifically is related to that anyways. This error indicates that either the database was not initialized successfully, or the config value in question (`Redis.cache_group`) was not set on creation. There may have been other log messages earlier in the record to indicate what the precursor to this exception was, but from this snippet alone I don't think the root cause can be fully determined.

I will try to replicate this on a fresh system. @jiagengliu I know it has been some time since you posted this issue, but if you are able, could you please reply with the method by which you installed Docker (IE: snap, deb package, compiled) ?

**Comment by jiagengliu** [comment]
Thank you! I'm not using Augur anymore, but if I recall correctly, I installed it with the deb package.
