### ISSUE TITLE
Frontend.log errors on 0.9.5

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#272]
**Describe the bug:**
Get this error: 

```python
module.js:549
    throw err;
    ^

Error: Cannot find module 'foreach'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/sean/github/augur/frontend/node_modules/define-properties/index.js:4:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```
**To Reproduce:**
Augur environment without Conda, but this looks more general. 

**Expected behavior:**
It works. 

**Screenshots**
nope.

**Desktop (please complete the following information):**
 Ubuntu

**Additional context**

**Comment by sgoggins** [comment]
fixed in pull request #273
