### ISSUE TITLE
Repo addition error 

### ISSUE THREAD

**Issue by cdolfi** [chaoss/augur#2787]
Traceback (most recent call last):
  File "/home/sean/github/virtualenv/rh-k12/lib/python3.11/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/sean/github/virtualenv/rh-k12/lib/python3.11/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sean/github/rh-k12/augur/tasks/frontend.py", line 41, in add_org_repo_list
    added = user.add_github_repo(group_name, url)[0]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sean/github/rh-k12/augur/application/db/models/augur_operations.py", line 461, in add_github_repo
    result = UserRepo.add_github_repo(session, repo_url, self.user_id, group_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sean/github/rh-k12/augur/application/db/models/augur_operations.py", line 883, in add_github_repo
    result = Repo.is_valid_github_repo(session, url)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sean/github/rh-k12/augur/application/db/models/augur_data.py", line 929, in is_valid_github_repo
    wait_until = int(result.headers.get("x-ratelimit-reset"))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

**Comment by Ulincsys** [comment]
Closed by #2812
