### ISSUE TITLE
ModuleNotFoundError: No module named 'gunicorn.six'

### ISSUE THREAD

**Issue by JerryKuan** [chaoss/augur#535]
Hi, augur team.
I had the problem when I execute `augur` in the augur_env. but it is ok when executed `make dev`.
this is the detail.
`ubuntu@10-24-2-162:/tmp/augur$ source $HOME/.virtualenvs/augur_env/bin/activate
(augur_env) ubuntu@10-24-2-162:/tmp/augur$ augur
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/augur_env/bin/augur", line 12, in <module>
    sys.exit(run())
  File "/home/ubuntu/.virtualenvs/augur_env/lib/python3.6/site-packages/Click-7.0-py3.6.egg/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.virtualenvs/augur_env/lib/python3.6/site-packages/Click-7.0-py3.6.egg/click/core.py", line 716, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/home/ubuntu/.virtualenvs/augur_env/lib/python3.6/site-packages/Click-7.0-py3.6.egg/click/core.py", line 641, in make_context
    self.parse_args(ctx, args)
  File "/home/ubuntu/.virtualenvs/augur_env/lib/python3.6/site-packages/Click-7.0-py3.6.egg/click/core.py", line 1086, in parse_args
    echo(ctx.get_help(), color=ctx.color)
  File "/home/ubuntu/.virtualenvs/augur_env/lib/python3.6/site-packages/Click-7.0-py3.6.egg/click/core.py", line 516, in get_help
    return self.command.get_help(self)
  File "/home/ubuntu/.virtualenvs/augur_env/lib/python3.6/site-packages/Click-7.0-py3.6.egg/click/core.py", line 879, in get_help
    self.format_help(ctx, formatter)
  File "/home/ubuntu/.virtualenvs/augur_env/lib/python3.6/site-packages/Click-7.0-py3.6.egg/click/core.py", line 898, in format_help
    self.format_options(ctx, formatter)
  File "/home/ubuntu/.virtualenvs/augur_env/lib/python3.6/site-packages/Click-7.0-py3.6.egg/click/core.py", line 1017, in format_options
    self.format_commands(ctx, formatter)
  File "/home/ubuntu/.virtualenvs/augur_env/lib/python3.6/site-packages/Click-7.0-py3.6.egg/click/core.py", line 1062, in format_commands
    cmd = self.get_command(ctx, subcommand)
  File "/tmp/augur/augur/runtime.py", line 47, in get_command
    None, None, ['cli'])
  File "/tmp/augur/augur/cli/run.py", line 8, in <module>
    from gunicorn.six import iteritems
ModuleNotFoundError: No module named 'gunicorn.six'`

OS:ubuntu 16.04

thanks~

**Comment by ccarterlandis** [comment]
Hi @JerryKuan, we've got a release coming in the next few days that will address the issue. For now, if you run `pip uninstall gunicorn` and then `pip install gunicorn==19.9.0`, that should get you working - if it doesn't, please let me know. So sorry about that!

**Comment by Nebrethar** [comment]
@ccarterlandis Has the release fixed the issue? Checking on the status fo the issue
