### ISSUE TITLE
dev: Clean Machine Installation Error : `~/.pgpass` No such file or directory

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#679]
**Describe the bug:**
When performing an installation on a new machine, I get this error: 

```
**********************************
Generating configuration file...
**********************************

2020-04-12 07:44:50 omaha augur[21213] WARNING %s could not be parsed, using defaults.
augur.config.json successfully created
Traceback (most recent call last):
  File "/home/sean/github/virtualenvs/augur-pivotal/bin/augur", line 11, in <module>
    load_entry_point('augur', 'console_scripts', 'augur')()
  File "/home/sean/github/virtualenvs/augur-pivotal/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/sean/github/virtualenvs/augur-pivotal/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/sean/github/virtualenvs/augur-pivotal/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sean/github/virtualenvs/augur-pivotal/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sean/github/virtualenvs/augur-pivotal/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sean/github/virtualenvs/augur-pivotal/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/sean/github/virtualenvs/augur-pivotal/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/sean/github/augur-pivotal/augur/cli/db.py", line 188, in load_data
    check_pgpass_credentials(app.config)
  File "/home/sean/github/augur-pivotal/augur/cli/db.py", line 237, in check_pgpass_credentials
    chmod(pgpass_file_path, stat.S_IWRITE | stat.S_IREAD)
FileNotFoundError: [Errno 2] No such file or directory: '/home/sean/.pgpass'
Traceback (most recent call last):
  File "/home/sean/github/virtualenvs/augur-pivotal/bin/augur", line 11, in <module>
    load_entry_point('augur', 'console_scripts', 'augur')()
  File "/home/sean/github/virtualenvs/augur-pivotal/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/sean/github/virtualenvs/augur-pivotal/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/sean/github/virtualenvs/augur-pivotal/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sean/github/virtualenvs/augur-pivotal/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sean/github/virtualenvs/augur-pivotal/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sean/github/virtualenvs/augur-pivotal/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/sean/github/virtualenvs/augur-pivotal/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/sean/github/augur-pivotal/augur/cli/db.py", line 181, in create_schema
    check_pgpass_credentials(app.config)
  File "/home/sean/github/augur-pivotal/augur/cli/db.py", line 237, in check_pgpass_credentials
    chmod(pgpass_file_path, stat.S_IWRITE | stat.S_IREAD)
FileNotFoundError: [Errno 2] No such file or directory: '/home/sean/.pgpass'
```

**To Reproduce:**
1. A Clean Ubuntu installation
2. Run `make install-dev`
3. see error

**Expected behavior:**
Should create the file or directory if it does not exist. 

**Desktop (please complete the following information):**
 - Ubuntu 18

**Additional context**
`dev` branch

**Comment by ccarterlandis** [comment]
I will update the script to create the `~/.pgpass` file if needed.

**Comment by sgoggins** [comment]
ALso, I lied. I was on Ubuntu 19. 
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```

**Comment by ccarterlandis** [comment]
This is fixed, once I have the other issues fixed as well I'll open a PR for all them
